platform :ios, '13.0'

target 'MUC_GP' do
  use_frameworks!
  pod 'TensorFlowLiteSwift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['ENABLE_PREVIEWS'] = 'YES'
    end
  end
end
